actresses = [
    {"name": "Andrea Jeremiah", "base_price": 2, "image": "images/1.jpg"},
    {"name": "Vani Bhojan", "base_price": 2, "image": "images/2.jpg"},
    {"name": "Vedhika", "base_price": 2, "image": "images/3.jpg"},
    {"name": "Pragya Nagra", "base_price": 2, "image": "images/4.jpg"},
    {"name": "Shruti Haasan", "base_price": 2, "image": "images/5.jpg"},
    {"name": "Anushka Shetty", "base_price": 2, "image": "images/6.jpg"},
    {"name": "Raashi Khanna", "base_price": 2, "image": "images/7.jpg"},
    {"name": "Regina Cassandra", "base_price": 2, "image": "images/8.jpg"},
    {"name": "Mamitha Baiju", "base_price": 2, "image": "images/9.jpg"},
    {"name": "Sreeleela", "base_price": 2, "image": "images/10.jpg"},
    {"name": "Anju Kurian", "base_price": 2, "image": "images/11.jpg"},
    {"name": "Trisha Krishnan", "base_price": 2, "image": "images/12.jpg"},
    {"name": "Ivana", "base_price": 2, "image": "images/13.jpg"},
    {"name": "Nivetha Thomas", "base_price": 2, "image": "images/14.jpg"},
    {"name": "Athulya Ravi", "base_price": 2, "image": "images/15.jpg"},
    {"name": "Anikha Surendran", "base_price": 2, "image": "images/16.jpg"},
    {"name": "Yashika Anand", "base_price": 2, "image": "images/17.jpg"},
    {"name": "Anaswara Rajan", "base_price": 2, "image": "images/18.jpg"},
    {"name": "Malavika Mohanan", "base_price": 2, "image": "images/19.jpg"},
    {"name": "Priyanka Arul Mohan", "base_price": 2, "image": "images/20.jpg"},
    {"name": "Meenakshi Chaudhary", "base_price": 2, "image": "images/21.jpg"},
    {"name": "Sneha", "base_price": 2, "image": "images/22.jpg"},
    {"name": "Meena", "base_price": 2, "image": "images/23.jpg"},
    {"name": "Priya Anand", "base_price": 2, "image": "images/24.jpg"},
    {"name": "Nazriya Nazim", "base_price": 2, "image": "images/25.jpg"},
    {"name": "Sai Pallavi", "base_price": 2, "image": "images/26.jpg"},
    {"name": "Rashmika Mandanna", "base_price": 2, "image": "images/27.jpg"},
    {"name": "Nayanthara", "base_price": 2, "image": "images/28.jpg"},
    {"name": "Bhagyashree Borse", "base_price": 2, "image": "images/29.jpg"},
    {"name": "Samantha Ruth Prabhu", "base_price": 2, "image": "images/30.jpg"},
    {"name": "Kayadu Lohar", "base_price": 2, "image": "images/31.jpg"},
    {"name": "Tamannaah Bhatia", "base_price": 2, "image": "images/32.jpg"},
    {"name": "Kajal Aggarwal", "base_price": 2, "image": "images/33.jpg"},
    {"name": "Alia Bhatt", "base_price": 2, "image": "images/34.jpg"},
    {"name": "Samyukta Menon", "base_price": 2, "image": "images/35.jpg"},
    {"name": "Deepika Padukone", "base_price": 2, "image": "images/36.jpg"},
    {"name": "Ananya Panday", "base_price": 2, "image": "images/37.jpg"},
    {"name": "Anupama Parameswaran", "base_price": 2, "image": "images/38.jpg"},
    {"name": "Krithi Shetty", "base_price": 2, "image": "images/39.jpg"},
    {"name": "Priya Bhavani Shankar", "base_price": 2, "image": "images/40.jpg"},
    {"name": "Amritha Aiyer", "base_price": 2, "image": "images/41.jpg"},
    {"name": "Reba Monica John", "base_price": 2, "image": "images/42.jpg"},
    {"name": "Saanve Meghna", "base_price": 2, "image": "images/43.jpg"},
    {"name": "Iswarya Menon", "base_price": 2, "image": "images/44.jpg"},
    {"name": "Pooja Hegde", "base_price": 2, "image": "images/45.jpg"},
    {"name": "Aishwarya Lekshmi", "base_price": 2, "image": "images/46.jpg"},
    {"name": "Preity Mukundhan", "base_price": 2, "image": "images/47.jpg"},
    {"name": "Neha Shetty", "base_price": 2, "image": "images/48.jpg"},
    {"name": "Mrunal Thakur", "base_price": 2, "image": "images/49.jpg"},
    {"name": "Keerthy Suresh", "base_price": 2, "image": "images/50.jpg"},
    {"name": "Kalyani Priyadharshan", "base_price": 2, "image": "images/51.jpg"},
    {"name": "Jhanvi Kapoor", "base_price": 2, "image": "images/52.jpg"},
    {"name": "Kriti Sanon", "base_price": 2, "image": "images/53.jpg"},
    {"name": "Kiara Advani", "base_price": 2, "image": "images/54.jpg"},
    {"name": "Srinidhi Shetty", "base_price": 2, "image": "images/55.jpg"},
    {"name": "Taapsee Pannu", "base_price": 2, "image": "images/56.jpg"},
    {"name": "Yami Gautham", "base_price": 2, "image": "images/57.jpg"},
    {"name": "Rakul Preet Singh", "base_price": 2, "image": "images/58.jpg"},
    {"name": "Nithya Menen", "base_price": 2, "image": "images/59.jpg"},
    {"name": "Eesha Rebba", "base_price": 2, "image": "images/60.jpg"},
    {"name": "Lavanya Tripathi", "base_price": 2, "image": "images/61.jpg"},
    {"name": "Ritu Varma", "base_price": 2, "image": "images/62.jpg"},
    {"name": "Shriya Saran", "base_price": 2, "image": "images/63.jpg"},
    {"name": "Aparna Das", "base_price": 2, "image": "images/64.jpg"},
    {"name": "Ileana D'Cruz", "base_price": 2, "image": "images/65.jpg"},
    {"name": "Mirnalini Ravi", "base_price": 2, "image": "images/66.jpg"},
    {"name": "Sanya Malhotra", "base_price": 2, "image": "images/67.jpg"},
    {"name": "Jacqueline Fernandez", "base_price": 2, "image": "images/68.jpg"},
    {"name": "Nora Fatehi", "base_price": 2, "image": "images/69.jpg"},
    {"name": "Sara Arjun", "base_price": 2, "image": "images/70.jpg"},
    {"name": "Rukmini Vasanth", "base_price": 2, "image": "images/71.jpg"},
    {"name": "Anu Emmanuel", "base_price": 2, "image": "images/72.jpg"},
    {"name": "Disha Patni", "base_price": 2, "image": "images/73.jpg"},
    {"name": "Amala paul", "base_price": 2, "image": "images/74.jpg"},
    {"name": "Aparna Balamurali", "base_price": 2, "image": "images/75.jpg"},
    {"name": "Madonna Sebastian", "base_price": 2, "image": "images/76.jpg"},
    {"name": "Aditi Rao Hydari", "base_price": 2, "image": "images/77.jpg"},
    {"name": "Nikhila Vimal", "base_price": 2, "image": "images/78.jpg"},
    {"name": "Aishwarya Rai", "base_price": 2, "image": "images/79.jpg"},
    {"name": "Divya Bharathi", "base_price": 2, "image": "images/80.jpg"},
    {"name": "Gauri G Kishan", "base_price": 2, "image": "images/81.jpg"},
    {"name": "Pranitha Subash", "base_price": 2, "image": "images/82.jpg"},
    {"name": "Shivani Narayanan", "base_price": 2, "image": "images/83.jpg"},
    {"name": "Mirna Menon", "base_price": 2, "image": "images/84.jpg"},
    {"name": "Ritika Singh", "base_price": 2, "image": "images/85.jpg"},
    {"name": "Parvathy Thiruvothu", "base_price": 2, "image": "images/86.jpg"},
    {"name": "Nandita Swetha", "base_price": 2, "image": "images/87.jpg"},
    {"name": "Shalini Pandey", "base_price": 2, "image": "images/88.jpg"},
    {"name": "Sara Ali Khan", "base_price": 2, "image": "images/89.jpg"},
    {"name": "Tripti Dimri", "base_price": 2, "image": "images/90.jpg"},
    {"name": "Megha Akash", "base_price": 2, "image": "images/91.jpg"},
    {"name": "Kashmira Pardeshi", "base_price": 2, "image": "images/92.jpg"},
    {"name": "Vaishnavi Chaitanya", "base_price": 2, "image": "images/93.jpg"},
    {"name": "Shraddha Kapoor", "base_price": 2, "image": "images/94.jpg"},
    {"name": "Wamiqa Gabbi", "base_price": 2, "image": "images/95.jpg"},
    {"name": "Shraddha Srinath", "base_price": 2, "image": "images/96.jpg"},
    {"name": "Nabha Natesh", "base_price": 2, "image": "images/97.jpg"},
    {"name": "Ketika Sharma", "base_price": 2, "image": "images/98.jpg"},
    {"name": "Ashika Ranganath", "base_price": 2, "image": "images/99.jpg"},
    {"name": "Anushka Sharma", "base_price": 2, "image": "images/100.jpg"}, 
]